### ISSUE TITLE
最新版用不了了,2.41

### ISSUE THREAD

**Issue by Neroscofee** [a244573118/WeChatIntercept#12]

**Comment by a244573118** [comment]
亲测2.4.2依然可用，您重新安装下。

**Comment by Neroscofee** [comment]
根据你最后的更新,适配微信版本2.3.29.我之前为了使用这个插件专门去找了个微信2.3.29的,之前找到该插件时微信最新版本为2.41,当时直接下载2.41是无法使用的,所以提交了这个问题.
现在我的操作是,将微信2.3.29直接版本升级到最新的2.4.2,仍然可以使用该插件.我的推测是,微信2.3.29里有的包内容代码或api,经过直接升级被保留了下来,所以可以使用,而我第一次单独下载2.41无法使用是因为没有2.3.29里的某些包(微信优化时删除了?)
