### ISSUE TITLE
希望添加一个免认证登陆

### ISSUE THREAD

**Issue by gassion** [a244573118/WeChatIntercept#16]
扫描二维码登陆之后，下次就自动登录。

**Comment by gassion** [comment]
@a244573118

**Comment by a244573118** [comment]
好的老哥！等后面空闲时间加上。

**Comment by gassion** [comment]
> 好的老哥！等后面空闲时间加上。

非常感谢！🤝

**Comment by a244573118** [comment]
老哥，免认证登录已加

**Comment by gassion** [comment]
> 老哥，免认证登录已加

非常感谢！

**Comment by gassion** [comment]
> 老哥，免认证登录已加
奈何我手残把微信升级成3.0.1了，安装之后闪退打不开哎，罪过罪过

**Comment by gassion** [comment]
> 官网下载最新版微信，Version. 3.0.2 (18028)

多谢  老哥

**Comment by a244573118** [comment]
3.0.3你安装下看是否支持，不支持的话我后面再更新，感觉这块微信应该不会更新特别频繁

**Comment by gassion** [comment]
我测试了安装微信就闪退了根本打不开。


原始邮件
***@***.***
***@***.***
***@***.***; State ***@***.***
发送时间:2021年5月11日(周二) 10:11
主题:Re: [a244573118/WeChatIntercept] 希望添加一个免认证登陆 (#16)


3.0.3你安装下看是否支持，不支持的话我后面再更新，感觉这块微信应该不会更新特别频繁

**Comment by gassion** [comment]
好的，谢谢


原始邮件
***@***.***
***@***.***
***@***.***; State ***@***.***
发送时间:2021年5月11日(周二) 10:16
主题:Re: [a244573118/WeChatIntercept] 希望添加一个免认证登陆 (#16)


好的！后面有空我更新下，现在如果你想使用的话可以从其他软件网站下载一个3.0.2版本的微信使用

**Comment by a244573118** [comment]
好的！后面有空我更新下，现在如果你想使用的话可以从其他软件网站下载一个3.0.2版本的微信使用
