### ISSUE TITLE
出现表情一直在加载

### ISSUE THREAD

**Issue by kaka77** [a244573118/WeChatIntercept#19]
使用防撤回，很多自定义表情显示一直在转圈加载。。。

**Comment by a244573118** [comment]
我这边倒是一直没遇到过这种情况，代码改动也没有改动过表情显示部分代码，是不是与网络情况有关系？

**Comment by kaka77** [comment]
> 我这边倒是一直没遇到过这种情况，代码改动也没有改动过表情显示部分代码，是不是与网络情况有关系？

应该不是，我的网络还可以，同一网络下，手机能查看那个表情，电脑转圈半天，过后一段时间那个表情正常显示了。
