### ISSUE TITLE
微信奔溃

### ISSUE THREAD

**Issue by aishuidedabai** [a244573118/WeChatIntercept#2]

**Comment by a244573118** [comment]
应用程序-微信-显示包内容-Contents-MacOS,查看是否生成WeChat，WeChat_backup，WeChatIntercept.framework这三个文件

**Comment by aishuidedabai** [comment]
已生成，依旧崩溃

**Comment by a244573118** [comment]
确定这三个文件都有吗？framework文件在里面吗？

**Comment by aishuidedabai** [comment]
$ ls
WeChat                    WeChatIntercept.framework WeChat_backup

是不是这三个

**Comment by a244573118** [comment]
是的，您微信版本多少？建议升到最新版，我的目前版本是2.3.25，升级之后重新执行install.sh，重启微信即可

**Comment by aishuidedabai** [comment]
没有用，试过了，https://mac.weixin.qq.com/  从这里下载的微信

**Comment by a244573118** [comment]
我刚从这里下载重新执行一次，没有问题的。。。我身边同事也都在用，很正常

**Comment by a244573118** [comment]
我刚才重现了一下这个问题，建议您删除文件夹中的WeChat和WeChatIntercept.framework文件，然后将WeChat_backup重命名为WeChat，然后重新执行install.sh，这样就没问题了

**Comment by aishuidedabai** [comment]
好像没有什么用

$ ./Install.sh
/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
安装成功！

<img width="998" alt="屏幕快照 2019-07-10 下午2 32 51" src="https://user-images.githubusercontent.com/18343966/60945986-a475ad80-a31f-11e9-8ec3-6a9c5f240abf.png">

**Comment by a244573118** [comment]
18518513258

**Comment by a244573118** [comment]
V:18518513258

**Comment by a244573118** [comment]
已更新，解决此问题。
