### ISSUE TITLE
3.2.0 安装完以后会导致程序无法运行

### ISSUE THREAD

**Issue by elixzhang** [a244573118/WeChatIntercept#28]
安装完以后会显示没有权限打开微信应用程序

**Comment by Merlini93** [comment]
> 安装完以后会显示没有权限打开微信应用程序

我也有这个问题

**Comment by jbone123** [comment]
早知道，插件不升级了，有没有办法把插件版本退回去啊，楼主

**Comment by a244573118** [comment]
更新下插件，我这上面插件更新了

**Comment by Merlini93** [comment]
> 更新下插件，我这上面插件更新了

版本是最新的，依然有这个问题

**Comment by liiitleboy** [comment]
> 更新下插件，我这上面插件更新了

作者你好，更新了，还是有权限问题

**Comment by harleyGit** [comment]
不行，M1的看不到 防撤回的消息，

**Comment by YuyangHYY** [comment]
Mac Catalina版本
微信3.2.0

安装后无法打开微信

**Comment by ahlblzk** [comment]
亲测 Version. 3.1.1 (18708)版本可用
截图功能仅第一次使用会有提示 按提示操作后可恢复正常

**Comment by a244573118** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by a244573118** [comment]
最新版本已更新
