### ISSUE TITLE
You do not have permission to open the application “WeChat”.

### ISSUE THREAD

**Issue by HenryChou007** [a244573118/WeChatIntercept#30]
open WeChat error ,info as below:
You do not have permission to open the application “WeChat”.
Contact your computer or network administrator for assistance.

system info:  Mac mini (M1, 2020)
WeChat Version: 3.2.0 (19439)

**Comment by 2990221345** [comment]
me to M1 ,uninstall shell，You can open it

**Comment by a244573118** [comment]
最新版本已更新
