### ISSUE TITLE
然后去掉ZY助手前缀？有办法吗

### ISSUE THREAD

**Issue by Chaos-coder** [a244573118/WeChatIntercept#32]

**Comment by maxfong** [comment]
二进制替换吧,类似这样
```
ZY助手拦截到
\u005a\u0059\u52a9\u624b\u62e6\u622a\u5230

🍑桃子哥拦截
\ud83c\udf51\u6843\u5b50\u54e5\u62e6\u622a
```
<img width="895" alt="WechatIMG443" src="https://user-images.githubusercontent.com/3784855/151277676-30963fbc-c91d-436b-8e27-c34a6365803a.png">

效果:
![WechatIMG477](https://user-images.githubusercontent.com/3784855/151277787-40523339-a550-4937-bc04-7efee4aac5e9.png)

**Comment by a244573118** [comment]
最新版本已更新，支持自定义前缀
