### ISSUE TITLE
3.2.2

### ISSUE THREAD

**Issue by heyuanjun** [a244573118/WeChatIntercept#33]
什么时候更新下版本呢

**Comment by a244573118** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fanweiq** [comment]
使用其他微信插件的最近都收到了官方的警告。你用这个有收到过吗

**Comment by MIkeeJY** [comment]
如何屏蔽微信更新啊？老弹窗啊 ，好烦

**Comment by a244573118** [comment]
最新版本已更新
