### ISSUE TITLE
安装后无法打开微信

### ISSUE THREAD

**Issue by Pph1220** [a244573118/WeChatIntercept#35]
MacOS版本:Monterey12.1
芯片:M1Pro
微信版本:3.2.2
期待作者更新

**Comment by a244573118** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by a244573118** [comment]
最新版本已更新

**Comment by 841791885** [comment]
大佬你好,最新的安装之后打不开微信

**Comment by a244573118** [comment]
微信版本多少？不是M1芯片的吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [a244573118/WeChatIntercept] 安装后无法打开微信 (Issue #35)





 
大佬你好,最新的安装之后打不开微信

**Comment by 841791885** [comment]
是3.3.1的 m1芯片的

**Comment by 841791885** [comment]
大佬会不会是我安装方式错了? 我git clone 然后找到那个.sh文件运行的

**Comment by a244573118** [comment]
是在项目文件夹下运行的吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上8:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [a244573118/WeChatIntercept] 安装后无法打开微信 (Issue #35)





 
大佬会不会是我安装方式错了? 我git clone 然后找到那个.sh文件运行的

**Comment by 841791885** [comment]
是的  就是cd进到项目里面找到.sh文件运行

**Comment by 841791885** [comment]
大佬有思路咩

**Comment by a244573118** [comment]
那应该没问题的，我不是M1芯片电脑，不清楚怎么回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上8:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [a244573118/WeChatIntercept] 安装后无法打开微信 (Issue #35)





 
是的  就是cd进到项目里面找到.sh文件运行

**Comment by a244573118** [comment]
M1芯片我这边没适配




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [a244573118/WeChatIntercept] 安装后无法打开微信 (Issue #35)





 
是3.3.1的 m1芯片的
