### ISSUE TITLE
微信3.3.1 无法使用

### ISSUE THREAD

**Issue by YuyangHYY** [a244573118/WeChatIntercept#39]
Macbook Pro2017 
OS：Catalina 10.15

安装后显示这个：
<img width="585" alt="截屏2022-03-2409 14 54" src="https://user-images.githubusercontent.com/19391002/159822703-7836fd42-173b-4d37-ac70-ae0398d2345e.png">

**Comment by faithup** [comment]
我这边安装后无法打开

**Comment by Merlini93** [comment]
我也不能用，我这边显示应用微信无法打开

MAC OS 12.3
MacBook Air M1

**Comment by a244573118** [comment]
> 我也不能用，我手机显示应用微信无法打开
> 
> MAC 操作系统 12.3 MacBook Air M1

M1芯片不支持的

**Comment by a244573118** [comment]
> Macbook Pro2017 操作系统：Catalina 10.15
> 
> 安装后显示这个： <img alt="截屏2022-03-2409 14 54" width="585" src="https://user-images.githubusercontent.com/19391002/159822703-7836fd42-173b-4d37-ac70-ae0398d2345e.png">

有没有提示无法打开“insert_dylib”，因为无法验证开发者？

**Comment by a244573118** [comment]
> 我现在安装后无法打开

有没有提示无法打开“insert_dylib”，因为无法验证开发者？

**Comment by a244573118** [comment]
已经适配最新版本
