### ISSUE TITLE
App Version: Version. 2.3.26 (12718) 测试奔溃

### ISSUE THREAD

**Issue by shimxx** [a244573118/WeChatIntercept#4]
RT

**Comment by a244573118** [comment]
崩溃详细日志可以发现看看吗？

**Comment by shimxx** [comment]
Process:               WeChat [56585]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.3.26 (12718)
App Item ID:           836500024
App External ID:       832257654
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [56585]
User ID:               501

Date/Time:             2019-10-17 17:26:13.901 +0800
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        F344E03A-FBFF-CD7B-8D16-9DD6BF40B5CF

Sleep/Wake UUID:       521CE11D-914F-4AC2-9A22-FC4B3C645D46

Time Awake Since Boot: 760000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: */WeChatIntercept.framework/WeChatIntercept
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: image not found

Binary Images:
       0x10d0df000 -        0x10f3b9fe7 +com.tencent.xinWeChat (2.3.26 - 12718) <63114BB7-A497-3506-9695-DFD88C24289B> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x10fe24000 -        0x10ff70ff7 +com.tencent.WCDB (1.0.3 - 1) <A0E92CA0-F987-3468-B85D-F8EFAF737360> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x11000c000 -        0x1100effff +com.Tencent.JietuFramework (1.0.0 - 10021) <7EE9E4A3-25F4-3A61-9F12-F2812475820B> /Applications/WeChat.app/Contents/Frameworks/JietuFramework.framework/Versions/A/JietuFramework
       0x11017b000 -        0x110181ff7 +com.tencent.MMLibHooks (1.0 - 1) <E3A28C7E-0BB9-3AE2-BB32-512191684C3B> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x110191000 -        0x1101b3ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1101d5000 -        0x1101f7ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x110220000 -        0x1102c0fff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x11d29f000 -        0x11d2dcdc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff964b7000 -     0x7fff96678fff  com.apple.avfoundation (2.0 - 1187.36) <8C7813BE-B548-33E3-A61E-FF1F1984386A> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff9671c000 -     0x7fff967e5ff3  com.apple.AVKit (1.1 - 356.12) <CFEBC4BF-8A1D-3AF2-A83F-D531C10A848E> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff977c4000 -     0x7fff9859dff3  com.apple.AppKit (6.9 - 1504.83.101) <EC7BD195-F9E1-3E43-820A-5FDD0B2B0B67> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff98ad2000 -     0x7fff98cdefff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <91D2BA22-B168-3A9A-9008-6FFC5A8FDC1E> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff98cdf000 -     0x7fff98cdffff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <8C0153FD-FEFF-309C-AACD-BF9657A31F8E> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff98e48000 -     0x7fff99222fff  com.apple.CFNetwork (811.5.4 - 811.5.4) <4DBF8932-6286-3B23-87D9-63615B9958D9> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff9923c000 -     0x7fff9923cfff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff996f4000 -     0x7fff996f4fff  com.apple.Cocoa (6.11 - 22) <85EDFBE1-75F0-369E-8CA8-C6A639B98FA6> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff99c89000 -     0x7fff9a122ff7  com.apple.CoreFoundation (6.9 - 1349.8) <09ED473E-5DE8-307F-B55C-16F6419236D5> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff9a123000 -     0x7fff9a7a5fff  com.apple.CoreGraphics (2.0 - 1070.22) <78E7C882-837D-3CC3-B221-767B999873CE> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff9a9ea000 -     0x7fff9aa4fff7  com.apple.corelocation (2101.0.63) <B76E6C13-E10B-3F2F-AFD7-DB2C0DEF6579> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff9aa50000 -     0x7fff9ab01fff  com.apple.CoreMedia (1.0 - 1907.59.1.5) <6CCDE81A-6992-33ED-A1D9-9D27A4C1E31F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff9ab4e000 -     0x7fff9ab4efff  com.apple.CoreServices (775.19 - 775.19) <7255917D-EFBB-3BE2-A8FD-DAD631BC0949> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff9b277000 -     0x7fff9b3c4ffb  com.apple.CoreText (352.0 - 544.15) <BF0EE575-BB7E-3BF9-9029-232B4ADC24E4> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff9b3c5000 -     0x7fff9b3faff3  com.apple.CoreVideo (1.8 - 235.3) <AC11D5FB-C77B-34F5-B942-F698E84C229F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff9b3fb000 -     0x7fff9b46cffb  com.apple.framework.CoreWLAN (11.0 - 1200.31) <E47C0568-E37B-3052-9E77-F0F371DCDE7F> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff9b701000 -     0x7fff9baa7ff3  com.apple.Foundation (6.9 - 1349.81) <730B7944-BB43-35D5-A546-9F6CCED4B9F3> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff9bc68000 -     0x7fff9bcfeff7  com.apple.framework.IOKit (2.0.2 - 1324.60.3) <7CE4C98B-107C-3AAA-B49A-F2ACFCBBF526> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff9bd58000 -     0x7fff9beb8fef  com.apple.ImageIO.framework (3.3.0 - 1599.10.2) <87AA4D39-0AFC-3A34-98EF-02710E2BF3CA> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff9c1aa000 -     0x7fff9cdb2ff3  com.apple.JavaScriptCore (12603 - 12603.2.4) <FFD37381-05F4-3907-BD31-74CFC3D7868F> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff9dea0000 -     0x7fff9deeeff7  com.apple.MultipeerConnectivity (135.3 - 135.3) <068FDF41-9BA2-39C4-98EF-5ED6167FE026> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff9eccb000 -     0x7fff9ecd9fff  com.apple.opengl (14.0.16 - 14.0.16) <27E7D76E-A26B-39F8-8CF2-AB57920776A3> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff9f82a000 -     0x7fff9f82afff  com.apple.quartzframework (1.5 - 21) <09455972-8A33-3D61-B193-BA7E7CF984CA> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff9f82b000 -     0x7fff9fa2bfff  com.apple.QuartzCore (1.11 - 453.39.3) <AB46D60D-17A8-3122-800E-2A9DA604FCBA> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff9fa2c000 -     0x7fff9fa81fff  com.apple.QuickLookFramework (5.0 - 720.7) <3BD7BA2F-924C-3EFF-B26E-3F930E62E6B4> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff9ff92000 -     0x7fffa0294ff7  com.apple.security (7.0 - 57740.60.18) <021AACF6-D15F-37E0-840B-88853684BA00> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fffa06bf000 -     0x7fffa072eff7  com.apple.SystemConfiguration (1.14 - 1.14) <2412CDE0-C317-31EA-8F53-7A58BBFCC720> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fffa072f000 -     0x7fffa0addfff  com.apple.VideoToolbox (1.0 - 1907.59.1.5) <75E2F901-572F-3FC8-A599-96A085EEBC88> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fffa2052000 -     0x7fffa23fdffb  com.apple.WebKit (12603 - 12603.2.4) <1CF8B545-5910-31BC-AA29-F89ADFD919F9> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fffadee2000 -     0x7fffadee3ffb  libSystem.B.dylib (1238.60.2) <FC9E9F13-3B18-305C-BE0A-97C7843652B0> /usr/lib/libSystem.B.dylib
    0x7fffae01c000 -     0x7fffae072ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
    0x7fffae4e9000 -     0x7fffae5dbff7  libiconv.2.dylib (50) <42125B35-81D7-3FC4-9475-A26DBE10884D> /usr/lib/libiconv.2.dylib
    0x7fffae5dc000 -     0x7fffae801ffb  libicucore.A.dylib (57165.0.1) <2931B842-2946-3576-AD1D-1CDA22FA1388> /usr/lib/libicucore.A.dylib
    0x7fffaeb90000 -     0x7fffaef62047  libobjc.A.dylib (709) <DC77AA6E-A4E4-326D-8D7F-82D63AA88F99> /usr/lib/libobjc.A.dylib
    0x7fffaefb8000 -     0x7fffaefd4ffb  libresolv.9.dylib (64) <A244AE4C-00B0-396C-98FF-97FE4DB3DA30> /usr/lib/libresolv.9.dylib
    0x7fffaf274000 -     0x7fffaf363ffb  libxml2.2.dylib (30.16) <D2A6861B-D9FA-3BFC-B664-830C3FCE6065> /usr/lib/libxml2.2.dylib
    0x7fffaf38e000 -     0x7fffaf39fff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib

Model: MacBookAir7,2, BootROM MBA71.0166.B26, 2 processors, Intel Core i5, 1.6 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.126.1a2)
Bluetooth: Version 5.0.4f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100 LAN, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by a244573118** [comment]
已更新，解决此问题。
