### ISSUE TITLE
微信3.4无法使用

### ISSUE THREAD

**Issue by loverto** [a244573118/WeChatIntercept#44]
微信3.4无法使用

**Comment by Hackergeek** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/9377994/167292193-543ce1f0-0c4a-47a4-8d28-13eb62b2a9de.png">
亲测可以正常使用

**Comment by UJohn** [comment]
停留在3.3.1就好了

**Comment by ForeverWorld** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/100790155/174706883-e76be6f1-5ca1-40d1-a56f-ea65a69647f6.png">
正常使用

**Comment by a244573118** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jingmei2** [comment]
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/100790155/174706883-e76be6f1-5ca1-40d1-a56f-ea65a69647f6.png">
> 
> 正常使用

我也是最新的3.4.1版本，出现了小助手了。但是我看了文档，没说【自定义防撤回提示前缀】需要什么规则去添加，求教

**Comment by a244573118** [comment]
没有规则，随意自定义就可以的

**Comment by a244573118** [comment]
已经适配最新版本
