### ISSUE TITLE
被强制更新了，什么时候可以支持一下 3.5.5 

### ISSUE THREAD

**Issue by wuliqiangqiang** [a244573118/WeChatIntercept#47]
被强制更新了，什么时候可以支持一下 3.5.5

**Comment by a244573118** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wuliqiangqiang** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

快看看吧！

**Comment by a244573118** [comment]
不好意思，最近比较忙，后面有空我更新下

**Comment by a244573118** [comment]
已经适配最新版本
