### ISSUE TITLE
2.3.29 (12948)

### ISSUE THREAD

**Issue by libowenstc** [a244573118/WeChatIntercept#5]
微信版本2.3.29 (12948)失效了

**Comment by a244573118** [comment]
重新运行下脚本，微信升级脚本就会失效

**Comment by libowenstc** [comment]
重新运行还是不行，你升级试了吗....

**Comment by a244573118** [comment]
我的微信没升级，我升级看看

**Comment by a244573118** [comment]
新版本确实有问题，最近比较忙，等我过两天看看再发一版，现在先下载老版本微信吧，2.3.27可以使用

**Comment by libowenstc** [comment]
好的，谢谢

**Comment by QingMings** [comment]
嗨，这个issus 有新情况么 2.3.29 (13326)

**Comment by a244573118** [comment]
> 嗨，这个issus有新情况么2.3.29（13326）

已更新

**Comment by a244573118** [comment]
> 好的，谢谢

2.3.29防撤回已更新
