### ISSUE TITLE
执行脚本失败

### ISSUE THREAD

**Issue by shixiaoxianga** [a244573118/WeChatIntercept#52]
-e 为了将ZY助手写入微信, 请输入密码 ： 
chmod: root: No such file or directory
chmod: Unable to change file mode on /Applications/WeChat.app: Operation not permitted

都是在报这个错误

**Comment by a244573118** [comment]
前面加个sudo试试

**Comment by shixiaoxianga** [comment]
> 前面加个sudo考试

sudo sh Install.sh 试了一样的结果

-e 为了将ZY助手写入微信, 请输入密码 ： 
chmod: root: No such file or directory
chmod: Unable to change file mode on /Applications/WeChat.app: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents/_CodeSignature: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents/_CodeSignature/CodeResources: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents/MacOS: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents/MacOS/Mini Program.app: Operation not permitted
chmod: Unable to change file mode on /Applications/WeChat.app/Contents/MacOS/Mini Program.app/Contents: Operation not permitted

**Comment by a244573118** [comment]
按下面步骤试试呢，cd到WeChatIntercept文件夹，将Install.sh文件拖到终端，输入密码回车

**Comment by shixiaoxianga** [comment]
> 

执行 crsutil disable这个命令就可以了。

**Comment by shixiaoxianga** [comment]
撤回的图片和表情好像查看不了

**Comment by a244573118** [comment]
我这边测试可以查看的

**Comment by shixiaoxianga** [comment]
> 我这边测试可以查看的

可以查看，不好意思是我搞错了。感谢插件已点start！
