### ISSUE TITLE
微信小程序打不开

### ISSUE THREAD

**Issue by chenjieya** [a244573118/WeChatIntercept#58]
微信版本：v3.8.0.17

这个项目还在维护吗？安装按成之后，小程序打不开了，没有反应。

OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 106.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

**Comment by daihuanqi** [comment]
新版本失效啦 v3.8.0。
Intel Core i7
